Workaround for openmpi-related issue on macOS caused by long $TMPDIR
Fixes the below style of error message from openMPI by shortening to /tmp

--------------------------------------------------------------------------
A system call failed during shared memory initialization that should
not have.  It is likely that your MPI job will now either abort or
experience performance degradation.

  Local host:  hostname
  System call: unlink(2) /var/folders/9n/zxtlxtln2vz3jb_j_vthvflh0000gq/T//ompi.hostname.503/pid.53106/1/vader_segment.hostname.503.e9010001.8
  Error:       No such file or directory (errno 2)
--------------------------------------------------------------------------

Identical simulation run 36 times with / without setting TMPDIR=/tmp:
Errored 28 times without and 0 with this workaround.